### ISSUE TITLE
Consider renaming project

### ISSUE THREAD

**Issue by snicoll** [infobip/infobip-bean-validation#2]
Thanks for open-sourcing your efforts on this!

I was wondering if you'd consider renaming the project? `spring-bean-validation-boot-starter` is a bit weird (3rd party contributions are usually suffixed with `spring-boot-starter`. I believe the reason for that choice is because you already have spring in the name and, IMO, that's the root of the issue.

How about `infobib-validation`? Is that too wide? You could have a module with the same name as the new repo `infobib-validation` with a `infobib-validation-spring-boot-starter`. As far as I can see the current "api" module doesn't depend on Spring anyway.

Thoughts?

**Comment by lpandzic** [comment]
Hi @snicoll, 
thank you for your kind words.

About the naming, let me first explain the reasoning behind the name. This library is built on top of a premise that it will always be used within a Spring application. This is the reason why it's in the name, to express that 'hard' requirement.

I'm not sure what exactly is your concern? Mentioning Spring in project (or modules) name? 
Or is it the clunkiness of the lengthy name (which I agree with)?
I see a lot of projects on Maven Central that contain Spring in their name and are not maintained by Spring team.

**Comment by snicoll** [comment]
There's no problem as long as it doesn't start with `spring`. What I mean is this is an issue because you have spring already in the name so you can't repeat it again for the "starter" suffix. Quoting myself

> 3rd party contributions are usually suffixed with spring-boot-starter

So, it is that and indeed the clunkiness of the lengthy name. "boot-starter" feels wrong to me, that's why I opened this issue.

Thanks for your consideration.

**Comment by lpandzic** [comment]
So, something like:
infobip-bean-validation
- infobip-bean-validation-api
- infobip-bean-validation-spring-boot-starter?

**Comment by snicoll** [comment]
I think this proposal is better than the current names. Thanks!
