### ISSUE TITLE
Why this library exists?

### ISSUE THREAD

**Issue by asarkar** [infobip/infobip-bean-validation#8]
It's not clear to me (I've read the README) what additional features this library provides on top of Spring Boot. I see that it sets up custom `MethodValidationPostProcessor` and `LocalValidatorFactoryBean`, but why? Can you explain why this library exists and what benefits someone would get OOTB by using it?

**Comment by lpandzic** [comment]
It provides features that don't exist in either Bean Validation or in Spring Boot starters such as:
- [SimpleConstraintValidator](https://github.com/infobip/infobip-bean-validation#-simpleconstraintvalidator)
- [Hibernate Validator Configuration Strategy](https://github.com/infobip/infobip-bean-validation#-hibernate-validator-configuration-strategy)
- predefined validation groups - Create, Update, Delete
- predefined validation sequence - ExpensiveSequence
- Out of the box composed annotations: @ValidatedService, @ValidatedRestController
- [simple override for thrown exception mapping](https://github.com/infobip/infobip-bean-validation#-constraintviolationexception-mapping)

When I get some free time on my hands I plan to open source an internal project we're using to translate bean validation annotations to class validator typescript decorators.

**Comment by asarkar** [comment]
- `SimpleConstraintValidator` is to avoid overriding empty `initialize`, which I suppose saves one line of code.
- I don't know the use of validation sequence, so can't comment on the usefulness of it.
- `ConstraintViolationException` mapping seems useful, but based on Spring Boot design, it can be done in a `ControllerAdvice`.

There's a library, `spring-lemon`, specifically, a module [spring-lemon-exceptions](https://github.com/naturalprogrammer/spring-lemon/tree/master/spring-lemon-exceptions) that handle validation exceptions quite extensively. That guy also has [a blog](https://www.naturalprogrammer.com/courses/332639/lectures/5397631) where he does a pretty good job of explaining what the library does and why. I stumbled across this library trying to understand if there's something additional that's done here, and my conclusion is that, it's not.

**Comment by lpandzic** [comment]
> SimpleConstraintValidator is to avoid overriding empty initialize, which I suppose saves one line of code.

It's pretty evident in https://github.com/infobip/infobip-bean-validation#-simpleconstraintvalidator that there's more than one line of code saved.
Second important thing is that `SimpleConstraintValidator` is a `FunctionalInterface` meaning you can define validator as a lambda.

I can't comment on `spring-lemon` as I haven't used it.
